### ISSUE TITLE
_simplot Error

### ISSUE THREAD

**Issue by fspinella** [gregparkes/BattleSimulator#2]
HI Greg! 
Thanks for this awesome battlesim!
I'm trying to implement it on my pc to use it in my D&D Campaigns, cause I find it awesome.

I'm following the tutorial and the error that is given when I run "battle.sim_jupyter()" is "name '_simplot' is not defined".

Is it a problem in a package?

Thank you!

**Comment by gregparkes** [comment]
Hi, thanks for your issue.

Yes you're right, I haven't worked on this project in over a year and there are a number of issues, most of which I have just nominally fixed. The issue you raise is due to me re-arranging the subfiles. This should now be fixed if you pull the latest work (don't use PyPI that's way out of date).

If you have further issues let me know.
